### ISSUE TITLE
decode() got an unexpected keyword argument 'cg_dtype'

### ISSUE THREAD

**Issue by zjq0455** [enyac-group/Quamba#5]
Hi,
Thank u for ur contributions for Mamba quantization. We face this issue when trying to run Quamba. Specifically,
![1731116480246](https://github.com/user-attachments/assets/a6c39e0c-a3a6-42d9-a1e6-f7926bf7a918)
Could u please give some suggestions on how to solve it?

**Comment by hychiang-git** [comment]
Please see the [line](https://github.com/enyac-group/mamba/blob/f03430887cf396b886695bf0eae6de8bdd30b5ff/mamba_ssm/utils/generation.py#L134) in `generation.py` from our [commit](https://github.com/enyac-group/mamba/tree/f03430887cf396b886695bf0eae6de8bdd30b5ff)

Would you use the [commit](https://github.com/enyac-group/mamba/tree/f03430887cf396b886695bf0eae6de8bdd30b5ff) and try to run it again? Thanks!

**Comment by zjq0455** [comment]
> Please see the [line](https://github.com/enyac-group/mamba/blob/f03430887cf396b886695bf0eae6de8bdd30b5ff/mamba_ssm/utils/generation.py#L134) in `generation.py` from our [commit](https://github.com/enyac-group/mamba/tree/f03430887cf396b886695bf0eae6de8bdd30b5ff)
> 
> Would you use the [commit](https://github.com/enyac-group/mamba/tree/f03430887cf396b886695bf0eae6de8bdd30b5ff) and try to run it again? Thanks!

It works! Thank you.
