### ISSUE TITLE
Problem when evaluating real_quant

### ISSUE THREAD

**Issue by hoanglocla9** [enyac-group/Quamba#6]
Hi,

I have problems when trying to evaluating real_quant models. 
For example, When I try to run the main.py  with real quantization. It always returns NaN with Perplexity.
I also tried to run chat.py with quantization model, and the returned prompt is nothing (only contains "<|endoftext|>").

**Comment by hychiang-git** [comment]
Hi,
Sorry for the late reply. I hope you have resolved the issue. Here is my reproduction.

For zero-shot evaluation, I run `python main.py state-spaces/mamba-130m real --batch_size 1 --task_list lambada_openai --eval_zero_shot --log_dir logs`

2024-12-07:18:10:47,894 INFO     [lm_eval_wrapper.py:71] 0-shot evaluation results: 
|    Tasks     |Version|Filter|n-shot|  Metric  | Value |   |Stderr|
|--------------|------:|------|-----:|----------|------:|---|-----:|
|lambada_openai|      1|none  |     0|perplexity|20.9752|±  |0.7202|
|              |       |none  |     0|acc       | 0.4143|±  |0.0069|


For perplexity, I run `python main.py state-spaces/mamba-130m real --batch_size 1 --ppl_dataset wikitext2 --eval_ppl --log_dir logs`

```
2024-12-07:18:12:15,673 INFO     [ppl_eval.py:82] pereplexity on wikitext2: 25.596424102783203
2024-12-07:18:12:15,691 INFO     [main.py:85] Saving result to logs/mamba-130m_int8.json
```


Full log is here: [log.txt](https://github.com/user-attachments/files/18049431/log.txt)
