### ISSUE TITLE
PPL of W8A4 is much better than that of FP16

### ISSUE THREAD

**Issue by zjq0455** [enyac-group/Quamba#8]
Hi authors,

Congratulations for getting a good score at ICLR2025.  

I discover that when I try to evaluate under **W8A4** using wikitext2 as the calibration set, **the ppl is even better than fp16**. Specifically, for mamba-2.8b:  wikitext2: 3.69, pile: 1.33;  For mamba-1.4b:  wikitext2: 1.2, pile: 1.56.  Do you know why this happen?

**Comment by hychiang-git** [comment]
Hi,

Thanks for your interest. Our implementation only supports W8A8. Honestly, we did not try W8A4. 

Since you have raised the issue, we did modify our code slightly to run W8A4. However, the W8A4 cannot produce meaningful results. Would you like to share your implementation?

**Comment by zjq0455** [comment]
> Hi,
> 
> Thanks for your interest. Our implementation only supports W8A8. Honestly, we did not try W8A4.
> 
> Since you have raised the issue, we did modify our code slightly to simulate W8A4 with fake quantization. However, the W8A4 cannot produce meaningful results. Would you like to share your implementation?

We only modify configure_weight_quant() and configure_act_quant() (line 124-147) in modelutils_mamba.py as follows:


def configure_weight_quant(model):

    for name, m in model.named_modules():
        if isinstance(m, (QLinearLayer, QConv1D, QSScan)):
            logging.debug(f"Set {name} to 8 bit quant.")
            m.configure(
                n_bits=8,
            )
            
def configure_act_quant(model, act_scales):
    for name, m in model.named_modules():
        if isinstance(m, QAct):
            (scale, base) = act_scales.get(name)
            if scale is None:
                raise ValueError(f"Static quantization requires scale for {name}, but got None. Please check the calibration process.")
            
            logging.debug(f"Configure QAct module: {name} with 8 bits quantization.")
            m.configure(
                n_bits = 4,
                sym = True,
                o_scales=scale, 
                o_base=base,
            )

Specifically, for smaller mamba such as mamba-130m, the ppl result is inf. And for larger mamba such as mamba-2.8b, the W8A4 is much better than FP16.

**Comment by zjq0455** [comment]
> Hi,
> 
> Thanks for your interest. Our implementation only supports W8A8. Honestly, we did not try W8A4.
> 
> Since you have raised the issue, we did modify our code slightly to simulate W8A4 with fake quantization. However, the W8A4 cannot produce meaningful results. Would you like to share your implementation?

We only modify configure_weight_quant() and configure_act_quant() (line 124-147) in modelutils_mamba.py as follows:

def configure_weight_quant(model):
    for name, m in model.named_modules():
        if isinstance(m, (QLinearLayer, QConv1D, QSScan)):
            logging.debug(f"Set {name} to 8 bit quant.")
            m.configure(
                n_bits=8,
            )

       
def configure_act_quant(model, act_scales):
    for name, m in model.named_modules():
        if isinstance(m, QAct):
            (scale, base) = act_scales.get(name)
            if scale is None:
                raise ValueError(f"Static quantization requires scale for {name}, but got None. Please check the calibration process.")
            
            logging.debug(f"Configure QAct module: {name} with 8 bits quantization.")
            m.configure(
                n_bits = 4,
                sym = True,
                
                o_scales=scale, 
                o_base=base,
            )

Specifically, for smaller mamba such as mamba-130m, the ppl result is inf. And for larger mamba such as mamba-2.8b, the W8A4 is much better than FP16.

**Comment by zjq0455** [comment]
> Hi,
> 
> Thanks for your interest. Our implementation only supports W8A8. Honestly, we did not try W8A4.
> 
> Since you have raised the issue, we did modify our code slightly to simulate W8A4 with fake quantization. However, the W8A4 cannot produce meaningful results. Would you like to share your implementation?

We only modify configure_weight_quant() and configure_act_quant() (line 124-147) in modelutils_mamba.py as follows:

![1733972897288](https://github.com/user-attachments/assets/3c606615-5be9-4eff-9c34-2ab96ac5293c)


Specifically, for smaller mamba such as mamba-130m, the ppl result is inf. And for larger mamba such as mamba-2.8b, the W8A4 is much better than FP16.

**Comment by hychiang-git** [comment]
We did the same modifications and did see inf ppl for mamba-130m. We did not try larger models. Just curious, how does the W8A4 2.8B model perform for the average accuracy?

Btw, would you kindly share how W8A4 be useful? From my perspective (and most of the research), storing and loading weights in/from memory are usually the major bottlenecks, especially when the batch size is small.

**Comment by zjq0455** [comment]
> We did the same modifications and did see inf ppl for mamba-130m. We did not try larger models. Just curious, how does the W8A4 2.8B model perform for the average accuracy?
> 
> Btw, would you kindly share how W8A4 is useful? From my perspective (and most of the research), storing and loading weights in/from memory are usually the major bottlenecks, especially when the batch size is small.

There exists bugs when evaluating the average accuracy and I have not solved yet...  

The reason why I tried W8A4 is that I would like to explore the quantization limit of mamba and make some enhancement based on your valuable framework. I tried W4A4 but the performance is unsatisfactory so I further increase the bitwidth of each component (weight and activation). Therefore I observe this unreasonable phenomenon (W8A4 is better than FP16), I dont know why this happen and consider whether there are some unnoticeable bugs in this framework.

**Comment by hychiang-git** [comment]
I will close this issue as it appears to be outside the scope of our repository.

**Comment by zjq0455** [comment]
> I will close this issue as it appears to be outside the scope of our repository.

OK, I consider it is necessary to check out your codes carefully to ensure there are no unnoticeable errors in your repository.

**Comment by hychiang-git** [comment]
Welcome to reopen the issue or submit a PR if you have any updates :raised_hands:

**Comment by khoatm98** [comment]
hi @hychiang-git , I tried to dump values of a weight tensor with w4a8 configuration for mamba-1.4b, it shows so big values instead of int16, do you know the reason behind?
Here is the code I used: print("embedding", self.embedding.weight.shape, self.embedding.weight) 
Here is the value dumped:
tensor([[ -863471162, -1731696542,  1766545290,  ..., -1971947687,
          1250588521,  1796826791],
        [ 1986365354, -1180023962, -1413851783,  ...,  1419230073,
          1165417352, -1749326252],
        [ 1771485607,  -382498966, -1771287415,  ..., -1989638554,
          1282775422, -1736796251],
        ...,
        [ 1702135690, -1702223001, -1178905732,  ...,   882351241,
          1148623750, -1800841372],
        [ 1717929882, -1433779640, -1413720679,  ...,  1687730570,
          1417128566, -2018875820],
        [ 1733589385, -1732693161, -1665379207,  ...,  1149680764,
           862435959, -1750448586]], device='cuda:0', dtype=torch.int32)

**Comment by hychiang-git** [comment]
We pack the 4-bit ints with torch.int32. (see [here](https://github.com/enyac-group/Quamba/blob/main/quamba/qEmbedding.py#L35))

This question does not seem to be relative to this thread. Please open a new issue for any follow-up questions.

**Comment by khoatm98** [comment]
I got it, thank you.
